### ISSUE TITLE
constant naming of the project

### ISSUE THREAD

**Issue by DenniJensen** [dennisvandehoef/easy-html-creator#11]
The name on the project is different in Github and RubyGems. 
`easy-html-creater` vs `easy_html_creater`. I prefer the first version (dash), it will be work on RubyGems to. (like `rspec-rails`)

**Comment by dennisvandehoef** [comment]
The name on rubygems (easy_html_creator) is the correct name following the  "naming guide lines", since (in the rara case) wenn you might whant to require it in your source code it would be `require 'easy_html_creator'` and not ` require 'easy::html::creator'`.

Saddly we learnd this after we created this github repro. Naming is every where equal, with the exception of github.

**Comment by dennisvandehoef** [comment]
Since we don't whant to invalid the links to this repro, I created a second repro with teh correct name, an explanation and a link to this repro.

https://github.com/dennisvandehoef/easy_html_creator
